kind: pipeline
name: talkier

steps:
- name: test
  image: node:11-alpine
  commands:
  - npm install
  - npm test

- name: publish  
  image: plugins/gcr
  settings:
    repo: getcolors/talkier
    dockerfile: docker/node/Dockerfile
    tags: latest
    json_key:
      from_secret: google_credentials

- name: deploy
  image: google/cloud-sdk:latest
  environment:
    PROJECT_ID: talkier
    COMPUTE_ZONE: us-east1-b
    google_credentials: 
      from_secret: google_credentials
  commands:
    - yes | apt-get install python3
    - python3 key_generate.py key.json
    - gcloud config set project $PROJECT_ID
    - gcloud config set compute/zone $COMPUTE_ZONE
    - gcloud auth activate-service-account --key-file key.json
    - gcloud compute ssh talkier
    - docker pull -t talkier gcr.io/getcolors/talkier:latest
    - docker run -d -p 3000:3000 talkier