kind: pipeline
name: talkier

steps:
- name: test
  image: node:11-alpine
  commands:
  - npm install
  - npm test

- name: publish  
  image: plugins/gcr
  settings:
    repo: getcolors/talkier
    dockerfile: docker/node/Dockerfile
    tags: latest
    json_key:
      from_secret: google_credentials

- name: deploy
  image: google/cloud-sdk:alpine
  environment:
    PROJECT_ID: getcolors
    COMPUTE_ZONE: us-east1-b
    google_credentials: 
      from_secret: google_credentials
  commands:
    - yes | apk add python3
    - python3 key_generate.py key.json
    - gcloud config set project $PROJECT_ID
    - gcloud config set compute/zone $COMPUTE_ZONE
    - gcloud auth activate-service-account --key-file key.json
    - gcloud compute ssh talkier --command="rm -rf ~/credentials"
    - gcloud compute ssh talkier --command="mkdir ~/credentials"
    - gcloud compute scp key.json talkier:~/credentials/key.json
    - gcloud compute ssh talkier --command="docker login -u _json_key -p “$(cat ~/credentials/key.json)” https://gcr.io"
    - gcloud compute ssh talkier --command="docker pull gcr.io/getcolors/talkier:latest"
    - gcloud compute ssh talkier --command="docker run -d -p 3000:3000 talkier"