kind: pipeline
name: talkier

steps:
- name: test
  image: node:11-alpine
  commands:
  - npm install
  - npm test

steps:
- name: publish  
  image: plugins/gcr
  settings:
    repo: project/getcolors
    dockerfile: docker/node/Dockerfile
    tags: latest
    json_key:
      from_secret: google_credentials