kind: pipeline
name: talkier

steps:
- name: test
  image: node:11-alpine
  commands:
  - npm install
  - npm test

- name: publish  
  image: plugins/gcr
  settings:
    repo: getcolors/talkier
    dockerfile: docker/node/Dockerfile
    tags: latest
    json_key:
      from_secret: google_credentials

- name: deploy
  image: tonglil/auth-gcloud
  commands:
    - auth-gcloud
    - gcloud compute ssh talkier --zone=us-east1-b
    - docker pull gcr.io/getcolors/talkier:latest
  secret: [google_credentials]
