kind: pipeline
name: talkier

steps:
- name: test
  image: node:11-alpine
  commands:
  - npm install
  - npm test

- name: publish  
  image: plugins/gcr
  settings:
    repo: getcolors/talkier
    dockerfile: docker/node/Dockerfile
    tags: latest
    json_key:
      from_secret: google_credentials

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: https://35.231.202.214/
    username: _json_key
    secrets: [ google_credentials ] 
    script:
      - docker run -d -p 3000:3000 gcr.io/getcolors/talkier:latest
