kind: pipeline
name: talkier

steps:
- name: test
  image: node:11-alpine
  commands:
  - npm install
  - npm test

- name: publish  
  image: plugins/gcr
  settings:
    repo: getcolors/talkier
    dockerfile: docker/node/Dockerfile
    tags: latest
    json_key:
      from_secret: google_credentials

- name: deploy
  image: google/cloud-sdk:alpine
  environment:
    GOOGLE_APPLICATION_CREDENTIALS:
      from_secret: google_credentials
  volumes:
    - $GOOGLE_APPLICATION_CREDENTIALS:~/.config/gcloud/application_default_credentials.json
  commands:
    - gcloud auth application-default print-access-token
    - gcloud compute ssh talkier --zone=us-central1-a
    - docker run -d -p 3000:3000 gcr.io/getcolors/talkier:latest
