kind: pipeline
name: talkier

steps:
- name: test
  image: node:11-alpine
  commands:
  - npm install
  - npm test

- name: publish  
  image: plugins/gcr
  settings:
    repo: getcolors/talkier
    dockerfile: docker/node/Dockerfile
    tags: latest
    json_key:
      from_secret: google_credentials

- name: deploy
  image: google/cloud-sdk:alpine
  secrets: ["google_credentials"]
  commands:
    - gcloud compute ssh talkier
    - docker run -d -p 3000:3000 gcr.io/getcolors/talkier:latest
    